import type { OrderStatus } from "@/types";

export const MOCK_DRIVERS = [
  {
    id: "d1",
    name: "יוסי כהן",
    phone: "050-1111111",
    status: "available" as const,
    vehicle: "רכב - Toyota Yaris",
    zone: "חיפה והקריות",
    lat: 32.794,
    lng: 34.989,
    rating: 4.9,
    totalDeliveries: 342,
    todayDeliveries: 8,
    todayEarnings: 520,
  },
  {
    id: "d2",
    name: "דוד לוי",
    phone: "050-2222222",
    status: "busy" as const,
    vehicle: "אופנוע - Honda",
    zone: "חיפה והקריות",
    lat: 32.82,
    lng: 35.01,
    rating: 4.7,
    totalDeliveries: 218,
    todayDeliveries: 5,
    todayEarnings: 340,
  },
  {
    id: "d3",
    name: "מוחמד חוסיין",
    phone: "050-3333333",
    status: "busy" as const,
    vehicle: "רכב - Skoda Octavia",
    zone: "עכו-נהריה",
    lat: 32.928,
    lng: 35.084,
    rating: 4.8,
    totalDeliveries: 456,
    todayDeliveries: 6,
    todayEarnings: 410,
  },
  {
    id: "d4",
    name: "אלי ברק",
    phone: "050-4444444",
    status: "on_break" as const,
    vehicle: "ואן - Renault Kangoo",
    zone: "הגליל",
    lat: 32.918,
    lng: 35.296,
    rating: 4.6,
    totalDeliveries: 189,
    todayDeliveries: 3,
    todayEarnings: 210,
  },
  {
    id: "d5",
    name: "רון שמעון",
    phone: "050-5555555",
    status: "available" as const,
    vehicle: "רכב - Hyundai i20",
    zone: "העמקים",
    lat: 32.684,
    lng: 35.303,
    rating: 4.5,
    totalDeliveries: 127,
    todayDeliveries: 4,
    todayEarnings: 280,
  },
  {
    id: "d6",
    name: "סאמר נסאר",
    phone: "050-6666666",
    status: "offline" as const,
    vehicle: "רכב - Kia Picanto",
    zone: "העמקים",
    lat: 32.699,
    lng: 35.295,
    rating: 4.9,
    totalDeliveries: 310,
    todayDeliveries: 0,
    todayEarnings: 0,
  },
];

export const DRIVER_STATUS_LABELS: Record<string, string> = {
  available: "פנוי",
  busy: "עסוק",
  on_break: "בהפסקה",
  offline: "לא מחובר",
};

export const DRIVER_STATUS_COLORS: Record<string, string> = {
  available: "#10B981",
  busy: "#F97316",
  on_break: "#F59E0B",
  offline: "#6B7280",
};

export const MOCK_ADMIN_ORDERS = [
  {
    id: "1",
    order_number: "DEL-A1B2C3-X1",
    status: "in_transit" as OrderStatus,
    service_type: "express",
    customer_name: "שרה אברהם",
    pickup_address: "חיפה, רח' הרצל 15",
    delivery_address: "כרמיאל, רח' הגליל 22",
    driver_name: "דוד לוי",
    driver_id: "d2",
    estimated_price: 89,
    created_at: "2026-02-26T08:30:00Z",
  },
  {
    id: "2",
    order_number: "DEL-D4E5F6-Y2",
    status: "pending" as OrderStatus,
    service_type: "same_day",
    customer_name: "יעקב מזרחי",
    pickup_address: "נשר, רח' הראשונים 7",
    delivery_address: "עכו, שוק הישן 3",
    driver_name: null,
    driver_id: null,
    estimated_price: 55,
    created_at: "2026-02-26T09:15:00Z",
  },
  {
    id: "3",
    order_number: "DEL-G7H8I9-Z3",
    status: "picked_up" as OrderStatus,
    service_type: "express",
    customer_name: "נועה גולן",
    pickup_address: "קריית ביאליק, דרך עכו 45",
    delivery_address: "נהריה, רח' הגעתון 12",
    driver_name: "מוחמד חוסיין",
    driver_id: "d3",
    estimated_price: 92,
    created_at: "2026-02-26T07:45:00Z",
  },
  {
    id: "4",
    order_number: "DEL-J0K1L2-W4",
    status: "delivered" as OrderStatus,
    service_type: "next_day",
    customer_name: "רונית שפירא",
    pickup_address: "חיפה, רח' מוריה 8",
    delivery_address: "צפת, רח' ירושלים 15",
    driver_name: "יוסי כהן",
    driver_id: "d1",
    estimated_price: 45,
    created_at: "2026-02-25T14:30:00Z",
  },
  {
    id: "5",
    order_number: "DEL-M3N4O5-V5",
    status: "pending" as OrderStatus,
    service_type: "economy",
    customer_name: "עמית בן דוד",
    pickup_address: "חיפה, רח' החלוץ 3",
    delivery_address: "טבריה, רח' הגליל 18",
    driver_name: null,
    driver_id: null,
    estimated_price: 35,
    created_at: "2026-02-26T10:00:00Z",
  },
  {
    id: "6",
    order_number: "DEL-P6Q7R8-U6",
    status: "confirmed" as OrderStatus,
    service_type: "same_day",
    customer_name: "לילך אלון",
    pickup_address: "קריית מוצקין, רח' ויצמן 22",
    delivery_address: "עפולה, רח' הנשיא 5",
    driver_name: null,
    driver_id: null,
    estimated_price: 62,
    created_at: "2026-02-26T09:45:00Z",
  },
  {
    id: "7",
    order_number: "DEL-S9T0U1-T7",
    status: "cancelled" as OrderStatus,
    service_type: "express",
    customer_name: "אורי פלד",
    pickup_address: "חיפה, שד' הציונות 10",
    delivery_address: "כרמיאל, רח' המלאכה 8",
    driver_name: null,
    driver_id: null,
    estimated_price: 85,
    created_at: "2026-02-25T16:00:00Z",
  },
  {
    id: "8",
    order_number: "DEL-V2W3X4-S8",
    status: "delivered" as OrderStatus,
    service_type: "next_day",
    customer_name: "מיכל ויס",
    pickup_address: "טירת כרמל, רח' הדקל 4",
    delivery_address: "נצרת, רח' הבשורה 7",
    driver_name: "רון שמעון",
    driver_id: "d5",
    estimated_price: 42,
    created_at: "2026-02-24T11:00:00Z",
  },
];

export const MOCK_CUSTOMERS = [
  {
    id: "c1",
    name: "שרה אברהם",
    email: "sara@example.com",
    phone: "050-7777777",
    type: "private" as const,
    totalOrders: 12,
    totalSpent: 680,
    lastOrder: "2026-02-26",
  },
  {
    id: "c2",
    name: "יעקב מזרחי",
    email: "yaakov@example.com",
    phone: "050-8888888",
    type: "business" as const,
    companyName: "מזרחי טכנולוגיות",
    totalOrders: 45,
    totalSpent: 3200,
    lastOrder: "2026-02-26",
  },
  {
    id: "c3",
    name: "נועה גולן",
    email: "noa@example.com",
    phone: "050-9999999",
    type: "private" as const,
    totalOrders: 8,
    totalSpent: 420,
    lastOrder: "2026-02-26",
  },
  {
    id: "c4",
    name: "רונית שפירא",
    email: "ronit@example.com",
    phone: "052-1111111",
    type: "private" as const,
    totalOrders: 3,
    totalSpent: 145,
    lastOrder: "2026-02-25",
  },
  {
    id: "c5",
    name: "עמית בן דוד",
    email: "amit@store.co.il",
    phone: "052-2222222",
    type: "business" as const,
    companyName: "חנות הגליל",
    totalOrders: 78,
    totalSpent: 5600,
    lastOrder: "2026-02-26",
  },
];

export const WEEKLY_ORDERS_DATA = [
  { day: "ראשון", orders: 32, revenue: 2100 },
  { day: "שני", orders: 28, revenue: 1850 },
  { day: "שלישי", orders: 35, revenue: 2400 },
  { day: "רביעי", orders: 30, revenue: 2050 },
  { day: "חמישי", orders: 42, revenue: 2900 },
  { day: "שישי", orders: 18, revenue: 1200 },
  { day: "שבת", orders: 0, revenue: 0 },
];
